cask_args appdir: "/Applications"
tap "homebrew/cask-fonts"
tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "melonamin/formulae"
tap "peripheryapp/periphery"

brew "mas"
mas "Codes", id: 1502020651
mas "Hand Mirror", id: 1502839586
mas "HomeCam", id: 1292995895
mas "Microsoft Remote Desktop", id: 1295203466
mas "NepTunes", id: 1006739057
mas "Peek", id: 1554235898
mas "TestFlight", id: 899247664


cask "1Password"
cask "font-fira-code"
cask "google-chrome"
cask "ghosty"
cask "homebrew/cask-drivers/qmk-toolbox"
cask "little-snitch"
cask "mimestream"
cask "netnewswire"
cask "notion"
cask "orion"
cask "outline-manager"
cask "pictogram"
cask "raycast"
cask "Slack"
cask "soundsource"
cask "zed"
cask "swiftbar"
cask "tailscale"
cask "telegram"
cask "tower"
cask "trex"
cask "via"
cask "visual-studio-code"
cask "xcodes"

brew "ctop"
brew "curl"
brew "curlie"
brew "docker-compose"
brew "docker-credential-helper"
brew "docker"
brew "exiftool"
brew "ffmpeg"
brew "fish"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "mint"
brew "mise"
brew "nyancat"
brew "starship"
brew "swiftformat"
brew "telnet"
brew "tig"
brew "tmux"
brew "websocat"
brew "wget"
brew "xcinfo"
brew "youtube-dl"
