[tools]
opencode = "latest"
pi = "latest"
actionlint = "latest"
air = "latest"
bun = "latest"
claude = "latest"
codex = "latest"
dust = "latest"
gh = "latest"
go = "latest"
golangci-lint = "latest"
goreleaser = "latest"
just = "latest"
node = "latest"
pnpm = "latest"
prek = "latest"
ripgrep = "latest"
sqlc = "latest"
swift = "latest"
swiftlint = "latest"
syft = "latest"
uv = "latest"
yarn = "latest"
zig = "latest"
"github:can1357/oh-my-pi" = "latest"
"go:github.com/mishamsk/whatsnew" = "v0.1.0"
"npm:@xai-official/grok" = "latest"
"npm:bb-app" = { version = "latest", trust_policy_excludes = ["pino@9.14.0", "@smithy/core@3.33.0", "@smithy/node-http-handler@4.11.0"], allow_builds = ["better-sqlite3", "node-pty"] }
